### ISSUE TITLE
Does it work on windows currently?

### ISSUE THREAD

**Issue by SmileLee123** [lmacken/pyrasite#142]
Is windows supported now？

**Comment by AlucardNosferatu** [comment]
No symbol table is loaded. Use the "file" command

I installed gdb and ran cmd manually, cmd showed the prompt above.

GNU gdb (GDB) 8.0.1

**Comment by user202729** [comment]
It should be supported, however the error reporting currently is not very good so the error could be anything.

Have you tried running the command as administrator?
