### ISSUE TITLE
Pyrasite freezes everytime I run

### ISSUE THREAD

**Issue by sollidsnake** [lmacken/pyrasite#46]
I installed in archlinux using the PKGBUILD in the pkgs/arch folder. If I run pyrasite-gui, the gui freezes when I click in any program on the left list. Basically the same thing happens if I run using pyrasite-shell - I get no output at all and I've to kill the process. Using just pyrasite nothing happens.

**Comment by lmacken** [comment]
Can you post the output of `pyrasite --verbose <pid> helloworld.py`?

**Comment by sollidsnake** [comment]
Oh, by running with the --verbose arg I saw I needed to enable ptrace with "echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope". Now it seems to work just fine. Thanks.

**Comment by lmacken** [comment]
Cool, I'm glad to hear it's working for you.
