### ISSUE TITLE
Inject/UnInject some code in anywhere

### ISSUE THREAD

**Issue by alex8224** [lmacken/pyrasite#52]
Hi
     pyrasite can inject some code anywhere?  
like Btrace (https://kenai.com/projects/btrace/pages/UserGuide) 
for example , I have a function like:

``` python
     def index(request):
         for k,v in request.iteritems():
              #inject code there, like: import pdb;pdb.set_trace()
              print(k,v)
```

when debug done, remove injected code.

Tks

**Comment by lmacken** [comment]
Pyrasite currently does not have the ability to inject itself into specific parts of the stack, but it is a feature I would welcome.

**Comment by alex8224** [comment]
Tks a lot.
