### ISSUE TITLE
meliae and cpython issues when installing

### ISSUE THREAD

**Issue by ryazwinski** [lmacken/pyrasite#9]
Seems to be an order dependency and maybe other issues, when doing an initial 'setup.py install'

**Comment by lmacken** [comment]
Yeah, there is definitely something odd with meliae's cython dep. Ideally we shouldn't even need to explicitly require Cython, but it feels like something is broken within meliae.

Needs more research.

**Comment by lmacken** [comment]
Dupe of Issue #3, I think.

**Comment by ryazwinski** [comment]
ah you're correct, my bad... I'll tinker w. #3, but not assign it because I'm not sure how much time I can put to it.

**Comment by lmacken** [comment]
Cool, thanks!
